sudo: required
services: 
  - docker

before_install:
  - docker build -t giuliaculoma/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t giuliaculoma/multi-client ./client
  - docker build -t giuliaculoma/multi-nginx ./nginx
  - docker build -t giuliaculoma/multi-server ./server
  - docker build -t giuliaculoma/multi-worker ./worker


