sudo: required
services: 
  - docker

before_install:
  - docker build -t myhome210190/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true myhome210190/react-test npm test

after_success:
  - docker build -t myhome210190/multi-client ./client
  - docker build -t myhome210190/multi-nginx ./nginx
  - docker build -t myhome210190/multi-server ./server
  - docker build -t myhome210190/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to Docker hub 
  - docker push myhome210190/multi-client
  - docker push myhome210190/multi-nginx
  - docker push myhome210190/multi-server
  - docker push myhome210190/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: eu-north-1 #example 
    app: multi-docker
    env: Multidocker-env
    bucket_name: #??
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY




